#define FOOTPRINT_PALETTE 2
#define FOOTPRINT_CHARACTER_BASE_BLOCK 0
#define FOOTPRINT_CHARACTER_OFFSET (16)
#define FOOTPRINT_CHARACTER_BLOCK_OFFSET (FOOTPRINT_CHARACTER_OFFSET * (8 * 8 / 2))
#define FOOTPRINT_SCREEN_BASE_BLOCK 28

#define LEVEL_PALETTE 3
#define LEVEL_CHARACTER_BASE_BLOCK 0
#define LEVEL_CHARACTER_OFFSET (32)
#define LEVEL_CHARACTER_BLOCK_OFFSET (LEVEL_CHARACTER_OFFSET * (8 * 8 / 2))
#define LEVEL_SCREEN_BASE_BLOCK 31

#define GLYPH_PALETTE 4
#define GLYPH_CHARACTER_BASE_BLOCK 0
#define GLYPH_CHARACTER_OFFSET (48)
#define GLYPH_CHARACTER_BLOCK_OFFSET (GLYPH_CHARACTER_OFFSET * (8 * 8 / 2))
#define GLYPH_SCREEN_BASE_BLOCK 26
// 62 characters

#define BACKGROUND_PALETTE 5
#define BACKGROUND_CHARACTER_BASE_BLOCK 0
#define BACKGROUND_CHARACTER_OFFSET (48 + (64 * 2))
#define BACKGROUND_CHARACTER_BLOCK_OFFSET (BACKGROUND_CHARACTER_OFFSET * (8 * 8 / 2))
#define BACKGROUND_SCREEN_BASE_BLOCK 25
// 64 characters

#define PATH_DEBUG_SCREEN_BASE_BLOCK 30

typedef struct character {
  void * start;
  unsigned int size;
} character_t;
