extern unsigned int _binary_music_gba_sketch_02v2__part_P1_voice_1_dfreq_start;
extern unsigned int _binary_music_gba_sketch_02v2__part_P1_voice_1_dfreq_size;

extern unsigned int _binary_music_gba_sketch_02v2__part_P1_voice_5_dfreq_start;
extern unsigned int _binary_music_gba_sketch_02v2__part_P1_voice_5_dfreq_size;

extern unsigned int _binary_music_gba_sketch_02v2__part_P2_voice_1_dfreq_start;
extern unsigned int _binary_music_gba_sketch_02v2__part_P2_voice_1_dfreq_size;
