extern unsigned int _binary_character_background_palette_start;
extern unsigned int _binary_character_background_palette_size;

extern unsigned int _binary_character_background_character_start;
extern unsigned int _binary_character_background_character_size;
