extern unsigned int _binary_character_bee_palette_start;
extern unsigned int _binary_character_bee_palette_size;

extern unsigned int _binary_character_bee_character_start;
extern unsigned int _binary_character_bee_character_size;
